### ISSUE TITLE
 Help integrating - Etekcity Fit 8S Smart Fitness Scale 

### ISSUE THREAD

**Issue by martiabernathey** [ronnnnnnnnnnnnn/etekcity_fitness_scale_ble#6]
This model looks very similar to yours, but I tried the integration and I'm getting this:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/etekcity_fitness_scale_ble/sensor.py", line 168, in async_setup_entry
    await coordinator.async_start()
  File "/config/custom_components/etekcity_fitness_scale_ble/coordinator.py", line 89, in async_start
    await self._async_start()
  File "/config/custom_components/etekcity_fitness_scale_ble/coordinator.py", line 75, in _async_start
    await self._client.async_start()
  File "/usr/local/lib/python3.13/site-packages/etekcity_esf551_ble/parser.py", line 118, in async_start
    await self._scanner.start()
  File "/usr/local/lib/python3.13/site-packages/etekcity_esf551_ble/bluetooth.py", line 81, in start
    await self._backend.start()
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/scanner.py", line 185, in start
    self._stop = await manager.active_scan(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/manager.py", line 423, in active_scan
    assert_reply(reply)
    ~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
```
I have tried the advice in the readme, but it doesn't seem to help. I'm running HA on a HomeAssistant Blue with a 
SABRENT Bluetooth dongle (BT-UB40) that's suggested as working out of the box in the HA documentation for Bluetooth integration. 

Any suggestions?

**Comment by ronnnnnnnnnnnnn** [comment]
Hi @martiabernathey, unfortunately I'm not sure there's too much I can do to help with the error as it seems to be more related to bluetooth and maybe some specific adapters rather than the integration itself. I'd try playing around some more with the BT adapter and service: disconnecting and reconnecting the adapter, restarting the BT service, powering it on/off etc. Other than that, I've also seen [this](https://github.com/home-assistant/core/issues/76544#issuecomment-1221272935), might be worth a try (and that whole thread in general).

Once you get over that issue, I'd love to know if the integration actually works with your model, and if not I'd be happy to try to see if I can easily add support for it.

**Comment by ronnnnnnnnnnnnn** [comment]
Closing for now. Will reopen if needed.

**Comment by ronnnnnnnnnnnnn** [comment]
@martiabernathey - Fit-8S is now supported, as of v0.5.0!
